var CACHE="sn-shell-4233",VER="4233",EARTH="/js/spacenet/earth-4204.js?v=4233",GUEST="/js/spacenet/earth-guest-4228.js?v=4233",MONEY="/js/spacenet/money-hide-4233.js?v=4233",TALK="/js/spacenet/talk-4232.js?v=4233",LANDJS="/js/spacenet/land-4232.js?v=4233",PIZZA="/js/spacenet/pizza-lock-4229.js?v=4233",FILL="/js/spacenet/fill-4233.js?v=4233",RINGS="/js/spacenet/assets/land-rings.json?v=4233",SHELL=["/","/index.html","/js/spacenet/sn-shell-4228.css?v=4233","/js/spacenet/app.js?v=4233","/js/spacenet/auth.js?v=4233",EARTH,GUEST,MONEY,TALK,LANDJS,PIZZA,FILL,RINGS,"/js/vendor/leaflet.js?v=4127","/js/vendor/leaflet.css?v=4127","/icon-192.png","/manifest.webmanifest"];
function isTile(t){return/tile\.openstreetmap\.org|tile\.openstreetmap\.de|openstreetmap\.fr\/hot/.test(t)}
function injectEarth(t){try{var e=t;
if(!/earth-4204\.js/.test(e)){if(/\/js\/spacenet\/auth\.js/.test(e))e=e.replace(/(<script src="\/js\/spacenet\/auth\.js[^"]*"><\/script>)/,'$1\n<script src="'+EARTH+'"><\/script>');else if(/\/js\/spacenet\/app\.js/.test(e))e=e.replace(/(<script src="\/js\/spacenet\/app\.js[^"]*"><\/script>)/,'$1\n<script src="'+EARTH+'"><\/script>');}
if(!/earth-guest-4228\.js/.test(e)&&/earth-4204\.js/.test(e))e=e.replace(/(<script src="\/js\/spacenet\/earth-4204\.js[^"]*"><\/script>)/,'$1\n<script src="'+GUEST+'"><\/script>');
if(!/money-hide-4233\.js/.test(e)&&/earth-guest-4228\.js/.test(e))e=e.replace(/(<script src="\/js\/spacenet\/earth-guest-4228\.js[^"]*"><\/script>)/,'$1\n<script src="'+MONEY+'"><\/script>');
if(!/talk-4232\.js/.test(e)){if(/earth-guest-4228\.js/.test(e))e=e.replace(/(<script src="\/js\/spacenet\/earth-guest-4228\.js[^"]*"><\/script>)/,'$1\n<script src="'+TALK+'"><\/script>');else if(/earth-4204\.js/.test(e))e=e.replace(/(<script src="\/js\/spacenet\/earth-4204\.js[^"]*"><\/script>)/,'$1\n<script src="'+TALK+'"><\/script>');}
if(!/land-4232\.js/.test(e)){if(/talk-4232\.js/.test(e))e=e.replace(/(<script src="\/js\/spacenet\/talk-4232\.js[^"]*"><\/script>)/,'$1\n<script src="'+LANDJS+'"><\/script>');else if(/earth-guest-4228\.js/.test(e))e=e.replace(/(<script src="\/js\/spacenet\/earth-guest-4228\.js[^"]*"><\/script>)/,'$1\n<script src="'+LANDJS+'"><\/script>');}
if(!/pizza-lock-4229\.js/.test(e)){if(/land-4232\.js/.test(e))e=e.replace(/(<script src="\/js\/spacenet\/land-4232\.js[^"]*"><\/script>)/,'$1\n<script src="'+PIZZA+'"><\/script>');else if(/talk-4232\.js/.test(e))e=e.replace(/(<script src="\/js\/spacenet\/talk-4232\.js[^"]*"><\/script>)/,'$1\n<script src="'+PIZZA+'"><\/script>');}
if(!/fill-4233\.js/.test(e)){if(/pizza-lock-4229\.js/.test(e))e=e.replace(/(<script src="\/js\/spacenet\/pizza-lock-4229\.js[^"]*"><\/script>)/,'$1\n<script src="'+FILL+'"><\/script>');else if(/land-4232\.js/.test(e))e=e.replace(/(<script src="\/js\/spacenet\/land-4232\.js[^"]*"><\/script>)/,'$1\n<script src="'+FILL+'"><\/script>');}
return e}catch(t){}return t}
self.addEventListener("install",function(t){self.skipWaiting(),t.waitUntil(caches.open(CACHE).then(function(t){return t.addAll(SHELL.map(function(t){return new Request(t,{cache:"reload"})})).catch(function(){})}).then(function(){return self.skipWaiting()}))});
self.addEventListener("activate",function(t){t.waitUntil(caches.keys().then(function(t){return Promise.all(t.map(function(t){if(t!==CACHE&&0!==t.indexOf("sn-tiles"))return caches.delete(t)}))}).then(function(){return self.clients.claim()}).then(function(){return self.clients.matchAll({type:"window"})}).then(function(t){t.forEach(function(t){if(t.navigate&&/\/boot(\/|\?|$)/.test(t.url||""))try{t.navigate("/?v="+VER+"&t="+Date.now())}catch(t){}})}))});
self.addEventListener("fetch",function(t){var e=t.request;if("GET"===e.method){var n=e.url,s="";try{s=new URL(n).pathname}catch(t){return}if(/^\/boot(\/|$)/.test(s))t.respondWith(Response.redirect("/?v="+VER+"&t="+Date.now(),302));else if(isTile(n))t.respondWith(caches.open("sn-tiles-1").then(function(t){return t.match(e).then(function(n){return n||fetch(e).then(function(n){return n&&n.ok&&t.put(e,n.clone()),n})})}));else{var c="/"===s||"/index.html"===s;t.respondWith(fetch(e,{cache:"no-store"}).then(function(t){if(!t||!t.ok)return t;if(c)return t.text().then(function(n){var s=injectEarth(n),c=new Headers(t.headers);c.set("Cache-Control","no-store, no-cache, must-revalidate"),c.set("X-Astranov-Build",VER);var r=new Response(s,{status:t.status,statusText:t.statusText,headers:c});return caches.open(CACHE).then(function(t){t.put(e,r.clone())}).catch(function(){}),r});if(/\/js\/spacenet\//.test(s)||"/sw.js"===s||0===s.indexOf("/js/spacenet/assets/")){var n=t.clone();caches.open(CACHE).then(function(t){t.put(e,n)}).catch(function(){})}return t}).catch(function(){return caches.match(e).then(function(t){return t?c?t.text().then(function(t){return new Response(injectEarth(t),{status:200,headers:{"Content-Type":"text/html; charset=utf-8","Cache-Control":"no-store"}})}):t:caches.match("/").then(function(t){return t?t.text().then(function(t){return new Response(injectEarth(t),{status:200,headers:{"Content-Type":"text/html; charset=utf-8","Cache-Control":"no-store"}})}):new Response("offline node",{status:503,headers:{"Content-Type":"text/plain"}})})})}))}}});
